### ISSUE TITLE
Add support for specifying environment variables in config files

### ISSUE THREAD

**Issue by jobottle** [hebench/frontend#52]
**Problem**
Currently some parameters specified in .config files should be adjusted based on the specs of the test machine. 
This can be a time consuming process/require use of additional tools to edit config files quickly with current code base.

**Proposal**
Proposed new feature is to enable specifying environment variables in config files as shown in this small example

 `5:`
        `name: NumThreads`
        `type: UInt64`
        `value:`
          `from: 1`
          `to: $NPROC`
         ` step: 1`

In this example $NPROC is assumed to be an environment variable and `to:` will be set to current value of NPROC 

**If the feature request is approved, would you be willing to submit a PR**  
Yes

**Comment by sidezrw** [comment]
I will look into it. Thanks for requesting.
