### ISSUE TITLE
Code base update breaks SEAL's  backend tutorial sample

### ISSUE THREAD

**Issue by jmbuzano** [hebench/frontend#56]
**Version Information (Put N/A for  Not Applicable)**
|          Software          |    Version(s)   |
| ---------------------------| --------------- |
| Linux                      |        5.10.60.1         |
| Git                        |      2.25.1           |
| CMake                      |        3.16.3         |
| Compiler (GCC, Clang, etc.)|     9.3.0            |
| GLIBC (ldd)                |        2.31         |
| Doxygen                    |        1.9.1         |
| HEBench Frontend           |       v0.6.2-beta          |
| HEBench API Bridge         |        v0.6.2-beta         |
| Reference Backend          |   .../docsrc/examples/backend_tutorials/seal/tutorial_backend/ |

**Describe the bug**  
SEAL's tutorial sample does not compile.

**To Reproduce**  
1. Go to .../docsrc/examples/backend_tutorials/seal/tutorial_backend/ 
2. Follow the steps to link your new backend
3. run cmake 
4. run make
5. You will get errors on the following lines:
```
.../src/tutorial_eltwiseadd_benchmark_seal.cpp:68
.../src/tutorial_eltwiseadd_benchmark_seal.cpp:97
.../src/tutorial_eltwiseadd_benchmark_seal.cpp:238
.../src/tutorial_eltwiseadd_benchmark_seal.cpp:239
.../src/tutorial_eltwiseadd_benchmark_seal.cpp:247
.../src/tutorial_eltwiseadd_benchmark_seal.cpp:287
```

**Expected behavior**  
For it to compile immediately.

**Screenshots**  

**Additional context**  
Base class in .../hebench/api_bridge/cpp/workload_params.hpp was modified, "n" lacks of the parentheses:
```
 w_params.n  -> w_params.n()
```

Also, line .../src/tutorial_eltwiseadd_benchmark_seal.cpp:287, must be modified to use GSL::spans properly:
```
assert(clear_param[sample_i] == w_params.n); -> assert(clear_param[sample_i].size() == w_params.n()); 
```

**Comment by sidezrw** [comment]
Thanks. We're looking into these.
